version: '3.8'

services:
  account-service:
    build: 
      context: ./account
    image: account-service
    environment:
      PORT: 5000
  catalog-service:
    build: 
      context: ./catalog
    image: catalog-service
    environment:
      PORT: 5000
  email-service:
    build: 
      context: ./email
    image: email-service
    environment:
      PORT: 5000
  payment-service:
    build: 
      context: ./payment
    image: payment-service
    environment:
      PORT: 5000
  portfolio-service:
    build: 
      context: ./portfolio
    image: portfolio-service
    environment:
      PORT: 5000
  wallet-service:
    build: 
      context: ./wallet
    image: wallet-service
    environment:
      PORT: 5000
  api-service:
    build: 
      context: ./api
    image: api-service
    environment:
      PORT: 5000
  db:
    image: postgres:17
    container_name: postgres-db
    restart: always

    # Set shared memory limit when using docker-compose. This is a good practice according to the official PostgreSQL documentation.
    shm_size: 128mb

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres-data: