apiVersion: v1
kind: ConfigMap
metadata:
  name: services-urls-config
data:
  ACCOUNT_SERVICE_URL: "http://account-service:5000"
  CATALOG_SERVICE_URL: "http://catalog-service:5000"
  EMAIL_SERVICE_URL: "http://email-service:5000"
  PAYMENT_SERVICE_URL: "http://payment-service:5000"
  PORTFOLIO_SERVICE_URL: "http://portfolio-service:5000"
  WALLET_SERVICE_URL: "http://wallet-service:5000"

