apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-service
  template:
    metadata:
      labels:
        app: portfolio-service
    spec:
      containers:
      - name: portfolio-service
        image: portfolio-service 
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: db-connexion-config
        - configMapRef:
            name: services-urls-config